### ISSUE TITLE
JavaScript Error when executing cast-web-api-desktop-1.2.1-armv7l.AppImage on Raspberry pi 3

### ISSUE THREAD

**Issue by smithp7117** [vervallsweg/cast-web-api#143]
When I try to install the Web cast api desktop I get the following error:

Uncaught Exemption:
TypeError: Error processing argument at index 0, convertion failure from /tmp/.mount_cast-wN84lc7/resources/app/img/icon-small.png at creatTray (/temp/.mount_cast-wN84lc7/resources/main.js:120:5) at App.emit (events.js:187:15)

I get the same error running nodejs version 14.6.0 or 12.18.3
Can anyone assist.

Thanks

**Comment by Pmsj80** [comment]
same problem , no one??

**Comment by MrRasmus** [comment]
I have the same problem on raspberry pi

**Comment by swdeason** [comment]
Did we find a solution to this issue? If so, please share.

Thanks
